blank_issues_enabled: false
contact_links:
  - name: Questions, Feedback, Suggestions
    url: https://github.com/spectreconsole/open-cli/discussions/new/choose
    about: Our preferred starting point if you have any questions, feedback, or suggestions.