# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./site/package-lock.json

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Build
        shell: bash
        run: |
          dotnet tool restore
          dotnet make ci --trace

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4